import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import RtkProvider from '@/commonComponents/RtkProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
   asd: React.ReactNode;
}) {
   return (
      <html lang='en'>
         <RtkProvider>
            <body className={inter.className}>{children}</body>
         </RtkProvider>
      </html>
   );
}
