import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import RtkProvider from '@/commonComponents/RtkProvider';
import MainHeader from './components/MainHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
   title: 'Easy Chat',
   description: 'Generated by Kimia Hasani',
   author: 'Kimia Hasani'
};

export default function RootLayout({ children }) {
   return (
      <html lang='en'>
         <RtkProvider>
            <body
               className={
                  inter.className +
                  ' container mx-auto bg-gradient-to-br from-orange-300 via-orange-400 to-red-400 min-h-screen'
               }
            >
               <MainHeader />
               {children}
            </body>
         </RtkProvider>
      </html>
   );
}
